services:
  postgres:
    image: postgres:16-alpine
    container_name: pm_postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pmpassword}
      POSTGRES_DB: ${POSTGRES_DB:-pm_db}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pm} -d ${POSTGRES_DB:-pm_db}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    volumes:
      - pm_volume:/var/lib/postgresql/data

    networks:
      - pm_net

  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
    networks:
      - pm_net


  migrator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: alembic upgrade head
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}          
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}                                                
      ARGON2_TIME_COST: ${ARGON2_TIME_COST:-3}
      ARGON2_MEMORY_COST: ${ARGON2_MEMORY_COST:-65536}                                       
      POSTGRES_USER: ${POSTGRES_USER:-pm}                                                    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pmpassword}
      POSTGRES_DB: ${POSTGRES_DB:-pm_db}           
      REDIS_URL: redis://redis:6379   
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
   
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - pm_net
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pm_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pm_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  redis:
    image: redis:7-alpine
    container_name: pm_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","--raw","incr","ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - pm_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}          
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}                                                
      ARGON2_TIME_COST: ${ARGON2_TIME_COST:-3}
      ARGON2_MEMORY_COST: ${ARGON2_MEMORY_COST:-65536}                                       
      POSTGRES_USER: ${POSTGRES_USER:-pm}                                                    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pmpassword}
      POSTGRES_DB: ${POSTGRES_DB:-pm_db}  
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

    volumes:
      - ./backend:/app
    
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - pm_net
networks:
  pm_net:

volumes:
  pm_volume:


