"""add_vault_history_and_soft_delete

Revision ID: 109f1a7cc47f
Revises: dbfd11491b6c
Create Date: 2026-05-26 23:22:44.985079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109f1a7cc47f'
down_revision: Union[str, Sequence[str], None] = 'dbfd11491b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('encrypted', sa.String(), nullable=False),
    sa.Column('iv', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vaults', sa.Column('is_deleted', sa.Boolean(), nullable=False,
  server_default='false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'is_deleted')
    op.drop_table('vault_history')
    # ### end Alembic commands ###
