"""add_refresh_token_rotation

Revision ID: dbfd11491b6c
Revises: 16c503b0664a
Create Date: 2026-05-26 21:36:57.563450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfd11491b6c'
down_revision: Union[str, Sequence[str], None] = '16c503b0664a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
      op.execute("DELETE FROM refresh_tokens")
      op.add_column('refresh_tokens', sa.Column('family_id', sa.String(), nullable=False))
      op.add_column('refresh_tokens', sa.Column('is_used', sa.Boolean(), nullable=False))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_used')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
